aws_access_key      =   ""
aws_secret_key      =   ""
private_key_path    =   "~/Downloads/yatharth-demo.pem"
key_name            =   "yatharth-demo"
bucket_name_prefix  =   "yatharth-bucket"
billing_code_tag    =   "ACCT12345"
environment_tag     =   "dev"